### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by ggrreeeedd** [chika0801/juicity-install#1]
nekoray:
INF run.go:79 > Requested QUIC_GO_ENABLE_GSO=false
可以正常使用

win自带杀毒报警
juicity-client.exe
Trojan:Win32/Wacatac.B!ml

**Comment by chika0801** [comment]
报病毒那个是WIN的误报

服务端 https://github.com/chika0801/juicity-install/blob/main/juicity.service#L9

这里 `Environment=QUIC_GO_ENABLE_GSO=true` 用着要快些，具体原因它网站有讲，你用 nekoray 我不清楚，我不用这软件了。

**Comment by ggrreeeedd** [comment]
thx

**Comment by chika0801** [comment]
GSO on-going suppor https://github.com/juicity/juicity/discussions/42

这有个说明
